
DEF_void_Dd_Dn_Dm(_, vadd_s8, int8x8_t, int8x8_t, int8x8_t)
DEF_void_Dd_Dn_Dm(_, vadd_s16, int16x4_t, int16x4_t, int16x4_t)
DEF_void_Dd_Dn_Dm(_, vadd_s32, int32x2_t, int32x2_t, int32x2_t)
DEF_void_Dd_Dn_Dm(_, vadd_s64, int64x1_t, int64x1_t, int64x1_t)
DEF_void_Dd_Dn_Dm(_, vadd_f32, float32x2_t, float32x2_t, float32x2_t)

DEF_void_Dd_Dn_Dm(_, vadd_u8,  uint8x8_t,  uint8x8_t,  uint8x8_t)
DEF_void_Dd_Dn_Dm(_, vadd_u16, uint16x4_t, uint16x4_t, uint16x4_t)
DEF_void_Dd_Dn_Dm(_, vadd_u32, uint32x2_t, uint32x2_t, uint32x2_t)
DEF_void_Dd_Dn_Dm(_, vadd_u64, uint64x1_t, uint64x1_t, uint64x1_t)

DEF_void_Qd_Qn_Qm(_, vaddq_s8,  int8x16_t, int8x16_t, int8x16_t)
DEF_void_Qd_Qn_Qm(_, vaddq_s16, int16x8_t, int16x8_t, int16x8_t)
DEF_void_Qd_Qn_Qm(_, vaddq_s32, int32x4_t, int32x4_t, int32x4_t)
DEF_void_Qd_Qn_Qm(_, vaddq_s64, int64x2_t, int64x2_t, int64x2_t)
DEF_void_Qd_Qn_Qm(_, vaddq_f32, float32x4_t, float32x4_t, float32x4_t)

DEF_void_Qd_Qn_Qm(_, vaddq_u8,  uint8x16_t, uint8x16_t, uint8x16_t)
DEF_void_Qd_Qn_Qm(_, vaddq_u16, uint16x8_t, uint16x8_t, uint16x8_t)
DEF_void_Qd_Qn_Qm(_, vaddq_u32, uint32x4_t, uint32x4_t, uint32x4_t)
DEF_void_Qd_Qn_Qm(_, vaddq_u64, uint64x2_t, uint64x2_t, uint64x2_t)

DEF_void_Qd_Dn_Dm(_, vaddl_s8, int16x8_t, int8x8_t, int8x8_t)
DEF_void_Qd_Dn_Dm(_, vaddl_s16, int32x4_t, int16x4_t, int16x4_t)
DEF_void_Qd_Dn_Dm(_, vaddl_s32, int64x2_t, int32x2_t, int32x2_t)

DEF_void_Qd_Dn_Dm(_, vaddl_u8, uint16x8_t, uint8x8_t, uint8x8_t)
DEF_void_Qd_Dn_Dm(_, vaddl_u16, uint32x4_t, uint16x4_t, uint16x4_t)
DEF_void_Qd_Dn_Dm(_, vaddl_u32, uint64x2_t, uint32x2_t, uint32x2_t)

DEF_void_Qd_Qn_Dm(_, vaddw_s8,  int16x8_t, int16x8_t, int8x8_t)
DEF_void_Qd_Qn_Dm(_, vaddw_s16, int32x4_t, int32x4_t, int16x4_t)
DEF_void_Qd_Qn_Dm(_, vaddw_s32, int64x2_t, int64x2_t, int32x2_t)

DEF_void_Qd_Qn_Dm(_, vaddw_u8,  uint16x8_t, uint16x8_t, uint8x8_t)
DEF_void_Qd_Qn_Dm(_, vaddw_u16, uint32x4_t, uint32x4_t, uint16x4_t)
DEF_void_Qd_Qn_Dm(_, vaddw_u32, uint64x2_t, uint64x2_t, uint32x2_t)

// next is vhadd_s8 ...
